export const ADD_USER = "ADD_USER";
export const ADD_DOCTOR = "ADD_DOCTOR";
export const ADD_CLIENT = "ADD_CLIENT";

export const SET_WAIT_LIST = "SET_WAIT_LIST";
export const SET_MASTERSHEET = "SET_MASTERSHEET";

// SCHEDULES

export const ADD_SCHEDULE = "ADD_SCHEDULE";

export const ADD_DOCTOR_AVAILABILITY = "ADD_DOCTOR_AVAILABILITY";
